### ISSUE TITLE
ubooquity no longer works with traefik

### ISSUE THREAD

**Issue by imro2** [joshuhn/media-docker#3]
Just tried to install ubooquity with traefik 1.6.6 based on your docker-compose.yml and I could not get it to work. It seems that the latest traefik changed the way segments are handled and with the configuration as is, traefik was load balancing between the library and admin port instead of assigning admin fronend to admin backend and library front end to library backend.

I had to assign different names to each backend segment 

     labels:
      - traefik.docker.network=proxied
      - traefik.enable=true
      - traefik.web.backend=ubooquity
      - traefik.web.frontend.rule=Host:ubooquity.${DOMAIN}
      - traefik.web.port=2202
      - traefik.admin.backend=ubooquity-admin
      - traefik.admin.frontend.rule=Host:admin-ubooquity.${DOMAIN}
      - traefik.admin.port=2203

Also I think [this](https://github.com/ShoGinn/homelab/wiki/Advanced-Traefik-Setups) setup is more seamless:

    labels:
      - traefik.docker.network=proxied
      - traefik.enable=true
      - traefik.web.backend=ubooquity
      - traefik.web.frontend.rule=Host:ubooquity.${DOMAIN}
      - traefik.web.port=2202
      - traefik.admin.backend=ubooquity-admin
      - "traefik.admin.frontend.rule=Host:ubooquity.${DOMAIN}; PathPrefix:/admin,/admin-res,/admin-api"
      - traefik.admin.port=2203

**Comment by imro2** [comment]
It actually could be related to containous/traefik#3744 and all that needs to happen to fix it is removing this:

     - traefik.backend=ubooquity

**Comment by joshuhn** [comment]
thanks for letting me know! the explicit traefik.backend label for the ubooquity container has been removed in commit https://github.com/joshuhn/media-docker/commit/16464515e3cb3718c72292248a49ebdc8ec8ba26 and i'm seeing this issue resolved in my testbed.
